import { UIProvider } from "@/components/providers/ui-provider";
import { Sidebar } from "@/components/sidebar/sidebar";
import "@/styles/globals.css";
import { viVN } from "@clerk/localizations";
import { ClerkProvider, auth } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = auth();

  return (
    <ClerkProvider
      localization={viVN}
      appearance={{
        elements: {
          footer: "hidden",
        },
      }}
    >
      <html lang="en">
        <body className={font.className}>
          <UIProvider>
            <main className="w-full h-full flex bg-gray-200 dark:bg-background">
              {userId && <Sidebar />}
              {children}
            </main>
          </UIProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
